name: zengen
description: A transformer to generate boilerplate code.
version: 0.2.0-dev
author: Alexandre Ardhuin <alexandre.ardhuin@gmail.com>
homepage: https://github.com/a14n/zengen
environment:
  sdk: '>=1.4.0-dev.6.9 <1.5.0'
dependencies:
  analyzer: any
  barback: '>=0.13.0 <0.14.0'
  quiver: '>=0.18.2 <0.19.0'
  code_transformers: any
dev_dependencies:
  unittest: '>=0.10.0 <0.11.0'
  path: '>=1.1.0 <2.0.0'
